# Generated by Django 3.2.6 on 2021-12-14 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackapp', '0004_auto_20210908_1224'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meet',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='female', max_length=255),
        ),
    ]
